# Generated by Django 5.2.4 on 2025-07-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Belge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_adi', models.CharField(help_text='Örn: Edebiyat, Tarih', max_length=100)),
                ('dosya', models.FileField(help_text='.txt uzantılı olmalı', upload_to='belgeler/')),
                ('yuklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('indekslendi_mi', models.BooleanField(default=False, help_text='Bu dosya RAG veritabanına eklendi mi?')),
            ],
        ),
    ]
